name: Goodreads reading list workflow

on:
  schedule:
    - cron: "30 4 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-goodreads:
    name: Update README with Goodreads reading list
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull currently reading books
        uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "200390160"
          shelf: "currently-reading"
          comment_tag_name: "GOODREADS-LIST"
          max_books_count: "10"
          template: "- [$title]($url) by $author (⭐️$average_rating)"

      - name: Pull completed reads
        uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "200390160"
          shelf: "read"
          comment_tag_name: "GOODREADS-READ-LIST"
          max_books_count: "10"
          template: "- [$title]($url) by $author (⭐️$average_rating)"

      - name: Pull to-read books
        uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "200390160"
          shelf: "to-read"
          comment_tag_name: "GOODREADS-TO-READ-LIST"
          max_books_count: "10"
          template: "- [$title]($url) by $author (⭐️$average_rating)"